import type { Metadata } from 'next';
import './globals.css';
import { Container } from '@/components/container';
import { Header } from '@/components/header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body>
                <div>
                    <Header />
                    <main className="pt-[var(--navigation-height)] bg-page-gradient">
                        {children}
                    </main>
                    <footer>
                        <Container>Footer Component</Container>
                    </footer>
                </div>
            </body>
        </html>
    );
}
